### ISSUE TITLE
DwC feed and drill back

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-tern#1]
**Purpose**: Occurrence records from AEKOS datasets are visible in ALA, and these records are adequately identified as being sourced from AEKOS and from a systematic dataset. Drill back through to AEKOS for rich details of methods.

**Work for ALA**
- [ ] Requirements detailed in whiteboard image below - possibly 3 days for 1 person in total (but can’t all be done at once, needs back and forward with AEKOS), may take longer, need to address needs around appropriate UI, branding etc. Iterative process.
- [ ] Complete all work required at the ALA end, such that the Darwin Core Feed from AEKOS can be picked up with minimal work (not waiting for Nov sprint) when it becomes available.
- [ ] Find out from AEKOS what form the DwC feed will come in.
- [ ] Keep in touch with AEKOS to access a prototype when available (from the BCCVL work); test; opportunity to come in as a third party to assist with validation etc.
- [ ] Think through and discuss with AEKOS the types of things ALA needs from the feed – e.g. stable identifiers, currency date etc., and communicate this back to AEKOS.
- [ ] Put in place attribution and branding for appropriate acknowledgement of AEKOS and data source.

**Suggestions from Lee**: The Darwin Core record components of AEKOS data in the ALA, with
Identification of the survey, survey type and a link direct to metadata about the survey in AEKOS. The ALA would only have metadata implied in the Darwin Core fields; and
The ability in the ALA to locate records (in addition to what we have now in terms of Darwin Core and other INDEXED fields) by survey and survey type. This is mandatory to enable for example, sites x species matrices to be generated for a survey.

**Work for AEKOS**
Open up access to DwC feed web service
Provide feedback on implementation and adequacy of attribution/drill back

**Actions needed before sprint:**
Miles/Mahmoud to work with Matt to have access to the DcW feed webservice opened up before 2 May 2016 [see below; Miles and Rebecca talked with Squid who will talk to AEKOS team about interactions during sprint period; prototype can be made available to ALA when ready, possibly within the sprint period]
Rebecca to contact Craig about proposed activities and potential availability of AEKOS tech staff to interact during the sprint period. [DONE - DcW feed due end June, prep work to implement when feed ready should go ahead this sprint]

ALA/AEKOS carriage (from Tech Workshop outcomes): Miles and Matt

![image](https://cloud.githubusercontent.com/assets/532845/14803248/41d2dda2-0b9b-11e6-812a-fb923c319138.png)
