### ISSUE TITLE
Methods catalogue and service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-tern#3]
**Purpose**: Provide a catalogue and service to store and access methods. 

**Work for ALA**
- [ ] Look at examples of methods in AEKOS to understand how methods are handled at present
- [ ] Talk with AEKOS to AEKOS intentions regarding extra granularity, so understand how the store we build needs to be extensible
- [ ] Build backend store and user interface to enter data (use BioCollect functionality? - this allows customised forms modifying database backend?)
- [ ] Build  service to interact with the store (need to talk to AEKOS to understand what they need)
- [ ] Load dump of methods from AEKOS???

**Work for AEKOS**
- [ ] Interact to provide information on granularity intentions
- [ ] Provide methods dump???
- [ ] Review and provide feedback on service???

**Actions needed before sprint:**
- [x] Miles (and Peter) connect with Anita to discuss and request methods dump to inform design [DONE - Rebecca and Miles have spoken with Craig/Squid. AEKOS will be working on adding granularity in methods in coming months, so store needs to be extensible to accommodate.]
- [ ] Rebecca to follow-up with Craig re timing of this work (Craig had expressed a preference to defer until Nov when the granularity work would be ready, however we should be able to accommodate through extensibility, and progress in May)

ALA/AEKOS carriage (from Tech Workshop outcomes): Peter and Anita (as SME)

**Comment by nickdos** [comment]
First pass (minimum viable product)
- gather data from SHaRED & Biocollect - fields: name, description [taxonomic focus, environment,category of method, literature reference]
- index with SOLR or equiv. (even DB lookup for first pass)
- simple app with web service that allows searching (and autocomplete)

**Comment by m-r-c** [comment]
I'd suggest using
- grails 2.5
- angularjs if/when there is a ui
- Elastic Search for indexing (see https://wiki.ala.org.au/wiki/Using-Elasticsearch-with-Grails, profile-service is a working example)
- ala-ws-security, ala-ws-plugin, ala-admin-plugin
