### ISSUE TITLE
Vocabulary service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-tern#5]
**Purpose**: Understand what [ANDS vocab service](https://vocabs.ands.org.au/) can provide to determine suitability for ALA needs and discuss with AEKOS to understand requirements for a shared(?) vocab service.

**Work for ALA**
- [ ] Investigate with ANDS to see what’s possible
- [ ] Discuss with AEKOS their requirements for a vocab service
- [ ] Develop solution for vocab service, via ANDS or otherwise

**Work for AEKOS**
- [ ] Time to interact on vocabulary requirements and potential solutions.

**Actions needed before sprint:**
- [x] Flag this discussion with AEKOS for the sprint period [DONE]

ALA/AEKOS carriage (from Tech Workshop outcomes): Miles and Squid

**Comment by nickdos** [comment]
ALA vocabs to be added to ANDS vocab service - see existing doc for list of existing vocabs (ask Miles)

Document how to add vocabs to ANDS (or other) and how it might be managed/curated.

**Comment by sadeghim** [comment]
Summarised some info about ANDS Vocab Service [here](https://github.com/AtlasOfLivingAustralia/ala-tern/wiki/ANDS-Vocab-Service).
Also, logged an issue on their ticketing system to followup regarding their service supporting ALA vocabs here:  https://jira.ands.org.au/browse/SD-9541

**Comment by sadeghim** [comment]
Updated the [wiki](https://github.com/AtlasOfLivingAustralia/ala-tern/wiki/ANDS-Vocab-Service) as ANDS has a new API for their vocab service supporting user supplied vocabs.
